"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-03 09:30:15.686731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_results',
    sa.Column('provider', sa.Enum('openai', 'ollama', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('schema_pass_rate', sa.Float(), nullable=True),
    sa.Column('retry_rate', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('hallucination_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'ollama', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('auto_saved', 'needs_review', 'reviewed', 'rejected', 'failed', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('raw_model_response', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('edited_output', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_run_id'), 'review_items', ['run_id'], unique=False)
    op.create_table('validation_logs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.Enum('schema', 'clinical', 'warning', 'critical', name='issuetype', native_enum=False, length=32), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_logs_run_id'), 'validation_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_logs_run_id'), table_name='validation_logs')
    op.drop_table('validation_logs')
    op.drop_index(op.f('ix_review_items_run_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('runs')
    op.drop_table('evaluation_results')
    # ### end Alembic commands ###
