"""phase10 routing and issue fields

Revision ID: 0002_phase10
Revises: 0001_initial
Create Date: 2026-07-03 13:14:31.425856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_phase10'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('routing_decision', sa.Enum('auto_save', 'human_review', 'reject', name='routingdecision', native_enum=False, length=32), nullable=True))
    op.add_column('runs', sa.Column('routing_reason', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('confidence_breakdown', sa.JSON(), nullable=True))
    op.add_column('validation_logs', sa.Column('severity', sa.Enum('warning', 'critical', name='severity', native_enum=False, length=32), nullable=True))
    op.add_column('validation_logs', sa.Column('rule_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_logs', 'rule_id')
    op.drop_column('validation_logs', 'severity')
    op.drop_column('runs', 'confidence_breakdown')
    op.drop_column('runs', 'routing_reason')
    op.drop_column('runs', 'routing_decision')
    # ### end Alembic commands ###
